use_frameworks!

target 'notification-centre_Example' do
  pod 'notification-centre', :path => '../'

  target 'notification-centre_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'URLImage', '~> 0.9.15'
    pod 'AWSAppSync', '~> 2.13.1'
  end
end
