//  Copyright © 2019 SEEK Limited. All rights reserved.
//

import Foundation

/**
 This enum should be kept up to date with the colors
 that exist within SEEKUIKit-Colors.xcassets
 */
public enum SKColorAsset: String, CaseIterable {
    case
    backgroundBrand,
    backgroundInfo,
    backgroundLogo,
    backgroundNeutral,
    backgroundPositive,
    backgroundPrimary,
    backgroundPromote,
    backgroundSecondary,
    badgeBackground,
    badgeText,
    buttonBackground,
    buttonBackgroundBrand,
    buttonBackgroundTertiary,
    buttonGhostOutline,
    buttonText,
    cardBackgroundPrimary,
    cardBackgroundSecondary,
    divider,
    dividerBackgroundBrand,
    iconClearNew,
    iconClear,
    iconClearError,
    iconError,
    iconLight,
    iconMedium,
    iconPositive,
    iconPromote,
    iconSelected,
    iconStarRating,
    iconStrong,
    iconStrongBackgroundBrand,
    link,
    pillBackground,
    pillErrorBackground,
    pillErrorText,
    pillNewBackground,
    pillNewText,
    pillText,
    pillUnselectedOutline,
    pressedOverlay,
    sklDivider,
    snackbarBackground,
    snackbarText,
    tabSelected,
    tabUnselected,
    textBackgroundBrand,
    textBrand,
    textError,
    textFieldBackground,
    textFieldBackgroundBrand,
    textInfo,
    textNeutral,
    textPlaceholder,
    textPositive,
    textPrimary,
    textPromote,
    textSecondary,
    textSecondaryBackgroundBrand,
    textViewed,
    widgetButton,
    widgetText
}
